sudo: required
language: bash
services:
- docker
before_install:
- make image-test
script:
- make test-in-container
env:
  global:
  - secure: Xbg+VWaPf02GSNbkg1kpQer5/i5sc/t5ntIRbKtL4BUkXpAFOHn7Ee88YRl8p6Ob+7qRuDNfzkaxSsWjUjuRT60GDnc3Lrbbcc0ZjabaVdc0OnAQMSWZnsVS3Fc3Mk9cRe5LNIUSV35Zf0lQUIkEJqRi+EPuaQYgeEGKxKRXOk4PpglkjbtJvaqEL4RE8dqaPkNTT6qsM2bLnL0q92Yh/ZMVN/7O00WCHAYtrDVtR7TM+9Do6z3nazOqUW6GdPsBJKLO6BDfTu4uxV/XMG7VcgX9L0wsEPAceQdtYXlnVQyyYxB6/TO6jfaN9zomj70o+JTAoB4UTCosicdPs2P1kyma/011rP4l8EWmxoikDcgA+rFseM5JJX5Wt4yLYi5X+aS12SQ9IaHwQiePuT96fFxRV8GJp8R41gTYrGi3bJB/xifK5JW9sLr5Ecficp3UGGkj3mSbQad8KfJSzNDxZAWu1NQEieT/jmEs+n3664JIWapRNPd+pSo3ew63lwo52XBNQp/8TZIiGFqGRenckEokX5b1kkr2qI66IN5HhdHPAyLoY9HCHASchY5HY3SnIt8mXfvSiD88pkFsT3jh6BMXKC1bUkADKKfPfQH3Lb1gedcTJZFXExAxvqtPzEG8LXO42Bn53SoLTfSiCd5jrbwg3pV5qmfk+486uAUXOro=
  - secure: kHLBmNa39znq9d+Egl5BaxQFaEhC/igKTzK2XpGDwovkDlGpi9tc5qq21vLVXilx93MFQdWt2RwbU7SPVc6WtMGUdIGl8pq3ebiaBj6TPeoY/f5zTAtTV2uDrBid1jCeaolpwxx21SoYda+0dBDeBTTo8bWEiu3ei1gB9mLiR3sJsmMjqoaKsMDGLnh+iLlDZj67lWNd6itee4E7sm+38Uac1oRa4dM+h6jS5lJ+ceO+sezNYR8qVz81XLOlE6h0O8+Um1/QqTro7J31DRewbxv1I0R/ut4by9ANNts75JGuEbPF2CaxaK5rTX/kORTCq0ngEOhpY3Lphe1JNfkqdPmnIBwooKcG+HQkjXRG0MxOVT/SHycvt25FyGP7KkLpxJPFx4OMg59k/k0I487EVwzxXIVuIW0aEFsneTqdhTRMRc4Vq5ADoWAd9DQHP78tGUwppjZ3P3vEVv3ArPPmpNxLfP7igBa0CSULm1dEr3I8A6i5YT1gtPiSYfcQcd/my6RGvyWDzAi3vhAEJfA9DbQHreMEHRCLnYwgOVelRuyti8tzSXi3RaiW9KE6JI599oIgNhxmA2ezhIqNH3pFqMehPtpvN0hsXv1Ek5XLcD3CRokdXfE4DsJiV9eDem0sEnsh5o9FbnR26WvMT7qYJxuVigBZDhkflrMrgbpdlGk=
